# conf/pipeline/imc2024/lightglue_aliked/lightgluealiked-038.yaml
type: detector_based

detector_based_pipeline:
  local_features:
    - type: lightglue_aliked
      lightglue_aliked:
        weight_path: ALIKED_LIGHTGLUE_N16
      resize:
        func: lightglue
        lg_resize: 1280

  shortlist_generator: 
    compat_version: v2
    global_descriptors:
      - type: cvnet 
        batch_size: 1
        num_workers: 1
        cvnet:
          weight_path: CVNET_R101
          depth: 101
          reduction_dim: 2048
      - type: dinov2
        batch_size: 1
        num_workers: 1
        dinov2:
          pretrained_model: DINOV2_BASE
    multiple_descs_fusion_type: concat-and-normalize
    similar_distance_threshold: 0.8
    topk: 30
  
  matcher:
    type: lightglue
    lightglue:
      weight_path: LIGHTGLUE_WITH_ALIKED_N16
      feature_name: aliked
      min_matches: 15
      width_confidence: -1.0
      depth_confidence: -1.0
      mp: true
  
  reconstruction:
    mapper_min_model_size: 3
    mapper_max_num_models: 2