# (n=20)
# lizard mttb
# 0.559 0.637
type: imc2024

imc2024_pipeline:
  shortlist_generator: 
    type: all_pairs
  
  pre_matching:
    matchers:
      - type: local_feature
        local_feature:
          type: lightglue_aliked
          lightglue_aliked:
            weight_path: ALIKED_LIGHTGLUE_N16
          resize:
            func: lightglue
            lg_resize: 960
        local_feature_matcher:
          type: lightglue
          lightglue:
            weight_path: LIGHTGLUE_WITH_ALIKED_N16
            feature_name: aliked
            min_matches: 15
            width_confidence: -1.0
            depth_confidence: -1.0
            mp: true
      - type: local_feature
        local_feature:
          type: lightglue_sift
          lightglue_sift:
            max_num_keypoints: 4096
        local_feature_matcher:
          type: lightglue
          lightglue:
            weight_path: LIGHTGLUE_WITH_SIFT
            feature_name: sift
            min_matches: 15
            width_confidence: -1.0
            depth_confidence: -1.0
            mp: true
  
  overlap_region_estimation:
    method: lof
    bidirectional: true
    bidirectional_merging: intersection
    bbox_expansion: 16
    border_padding: 8
    lof_n_neighbors: 100
  
  masking:
    make_watermark_masks: true
    watermark_overlap_delta: 10
    watermark_border_delta: 30
    rerun_overlap_estimation: true
  
  shortlist_updater:
    type: pre_matching
    pre_matching:
      match_threshold: 50
      aggregation_type: union
      global_descriptors:
        - type: cvnet 
          similar_distance_threshold: 0.6
          batch_size: 1
          num_workers: 1
          cvnet:
            weight_path: CVNET_R101
            depth: 101
            reduction_dim: 2048
        #- type: dinov2
        #  similar_distance_threshold: 0.2
        #  batch_size: 1
        #  num_workers: 1
        #  dinov2:
        #    pretrained_model: DINOV2_BASE
  
  local_features:
    - type: lightglue_aliked_tile
      lightglue_aliked_tile:
        weight_path: ALIKED_LIGHTGLUE_N16
        max_tile_size: 1280
        implement_version: v2
        max_num_keypoints: 4096
        detection_threshold: 0.01
        topk_after_merge: 4096
        threshold_after_merge: 0.05

  local_feature_matchers:
    - type: lightglue
      lightglue:
        weight_path: LIGHTGLUE_WITH_ALIKED_N16
        feature_name: aliked
        min_matches: 15
        width_confidence: -1.0
        depth_confidence: -1.0
        mp: true

  detector_free_matchers: []

  reconstruction:
    use_localize_sfm: true
    mapper_min_model_size: 3
    mapper_max_num_models: 2