# conf/pipeline/imc2024/_research_only/ensemble3/lightgluealiked-gimsuperpoint-gimdkm-001.yaml
# w/o feaure_track: 0.598
# w/ feaure_track: 0.598

type: imc2024

imc2024_pipeline:
  shortlist_generator: 
    type: all_pairs
  
  pre_matching:
    matchers:
      - type: local_feature
        local_feature:
          type: lightglue_aliked
          lightglue_aliked:
            weight_path: ALIKED_LIGHTGLUE_N16
          resize:
            func: lightglue
            lg_resize: 960
        local_feature_matcher:
          type: lightglue
          lightglue:
            weight_path: LIGHTGLUE_WITH_ALIKED_N16
            feature_name: aliked
            min_matches: 15
            width_confidence: -1.0
            depth_confidence: -1.0
            mp: true
      - type: local_feature
        local_feature:
          type: lightglue_sift
          lightglue_sift:
            max_num_keypoints: 4096
        local_feature_matcher:
          type: lightglue
          lightglue:
            weight_path: LIGHTGLUE_WITH_SIFT
            feature_name: sift
            min_matches: 15
            width_confidence: -1.0
            depth_confidence: -1.0
            mp: true
  
  overlap_region_estimation:
    method: lof
    bidirectional: true
    bidirectional_merging: intersection
    bbox_expansion: 16
    border_padding: 8
    lof_n_neighbors: 100
  
  masking:
    make_watermark_masks: true
    watermark_overlap_delta: 10
    watermark_border_delta: 30
    rerun_overlap_estimation: true
  
  shortlist_updater:
    type: pre_matching_topk
    pre_matching_topk:
      topk: 3
      path_length_for_additional_pairs: 2
      satisfied_edges_threshold: 6
      global_descriptors:
        - type: dinov2_salad
          similar_distance_threshold: 1.1
          batch_size: 1
          num_workers: 0
          dinov2_salad:
            weight_path: DINOV2_SALAD
            image_size: [322, 322]
        #- type: cvnet 
        #  similar_distance_threshold: 0.6
        #  batch_size: 1
        #  num_workers: 1
        #  cvnet:
        #    weight_path: CVNET_R101
        #    depth: 101
        #    reduction_dim: 2048
        #- type: dinov2
        #  similar_distance_threshold: 0.2
        #  batch_size: 1
        #  num_workers: 1
        #  dinov2:
        #    pretrained_model: DINOV2_BASE
  
  local_features:
    - type: lightglue_aliked
      lightglue_aliked:
        weight_path: ALIKED_LIGHTGLUE_N16
      resize:
        func: lightglue
        lg_resize: 1280
    - type: gim_superpoint
      gim_superpoint:
        weight_path: GIM_SUPERPOINT_LIGHTGLUE
        max_num_keypoints: 4096
      resize:
        func: gim
        gim_resize: 1280

  local_feature_matchers:
    - type: lightglue
      lightglue:
        weight_path: LIGHTGLUE_WITH_ALIKED_N16
        feature_name: aliked
        min_matches: 15
        width_confidence: -1.0
        depth_confidence: -1.0
        mp: true
    - type: gim_lightglue
      gim_lightglue:
        weight_path: GIM_SUPERPOINT_LIGHTGLUE
        min_matches: 15

  detector_free_matchers:
    - type: gim_dkm
      mkpts_decoupling_method: detector_free_sfm
      cropper_type: overlap-or-roi
      #matching_filter:
      #  type: feature_track
      gim_dkm:
        weight_path: GIM_DKM
        height: 512
        width: 512
        upsample_preds: false
        sample_nums: 5000
        topk: 1024
        verification:
          threshold: 0.25
          confidence: 0.99999
          max_iters: 40000
          method: magsac

  reconstruction:
    use_localize_sfm: true
    mapper_min_model_size: 3
    mapper_max_num_models: 3