# AMI: 0.6767041772423499
type: connected_component
connected_component:
  global_desc:
    global_desc_model: dinov2
    batch_size: 8
    dinov2:
      pretrained_model: DINOV2_BASE
  topk: 5
  dist_threshold: 0.3
  degree_threshold: 2