# AMI: 0.5366329844543226
type: connected_component
connected_component:
  global_desc:
    global_desc_model: dinov2
    batch_size: 8
    dinov2:
      pretrained_model: DINOV2_BASE
      options:
        pooling_type: mean
  topk: 5
  dist_threshold: 0.9