# AMI: 0.4709069868726862
type: connected_component
connected_component:
  global_desc:
    global_desc_model: mast3r_retrieval_spoc
    batch_size: 1
    mast3r_retrieval_spoc:
      mast3r:
        weight_path: MAST3R
        retrieval_weight_path: MAST3R_RETRIEVAL
        retrieval_codebook_path: MAST3R_RETRIEVAL_CODEBOOK
      global_desc_type: retrieval_spoc
  topk: 5
  dist_threshold: 0.8