# conf/pipeline/imc2025/lightgluealiked/lightgluealiked-007.yaml
# ------------------------------------
# ETs: score=67.15% (mAA=51.92%, clusterness=95.00%)
# stairs: score=5.26% (mAA=2.78%, clusterness=50.00%)
# Average over all datasets: score=36.20% (mAA=27.35%, clusterness=72.50%)
# Computed metric in: 0.62 sec.
# final_score: (36.2048773766878, 36.2048773766878, 0.0)
# ------------------------------------
# ETs: score=63.84% (mAA=48.08%, clusterness=95.00%)
# stairs: score=5.26% (mAA=2.78%, clusterness=50.00%)
# Average over all datasets: score=34.55% (mAA=25.43%, clusterness=72.50%)
# Computed metric in: 0.68 sec.
# final_score: (34.553621958121106, 34.553621958121106, 0.0)
# ------------------------------------
type: imc2025

imc2025_pipeline:
  local_features:
    - type: lightglue_aliked
      lightglue_aliked:
        weight_path: ALIKED_LIGHTGLUE_N16
      resize:
        func: lightglue
        lg_resize: 1280

  local_feature_matchers:
    - type: lightglue
      lightglue:
        weight_path: LIGHTGLUE_WITH_ALIKED_N16
        feature_name: aliked
        min_matches: 15
        width_confidence: -1.0
        depth_confidence: -1.0
        mp: true

  shortlist_generator: 
    type: global_desc
    global_desc_model: dinov2
    global_desc_batch_size: 1
    global_desc_num_workers: 1
    global_desc_similar_distance_threshold: 0.3
    global_desc_topk: 30
    global_desc_fallback_threshold: 30
    global_desc_remove_swapped_pairs: true
    global_desc_num_refills_when_no_matches: 30
    dinov2:
      pretrained_model: DINOV2_BASE
  
  reconstruction:
    fill_zero_Rt: false
    fill_nan_Rt: false
    fill_nearest_position: false
    mapper_min_model_size: 3
    mapper_max_num_models: 25
  
  clustering:
    type: connected_component
    connected_component:
      global_desc:
        global_desc_model: dinov2
        batch_size: 8
        dinov2:
          pretrained_model: DINOV2_BASE
          options:
            pooling_type: cls
      topk: 5
      dist_threshold: 0.9