# conf/pipeline/imc2024/ensemble3/lightgluealiked-dedode-hardnet-mtldesc-sfd2-002.yaml
# (fast)

type: imc2024

imc2024_pipeline:
  shortlist_generator: 
    type: all_pairs
  
  pre_matching:
    matchers:
      - type: local_feature
        local_feature:
          type: lightglue_aliked
          lightglue_aliked:
            weight_path: ALIKED_LIGHTGLUE_N16
          resize:
            func: lightglue
            lg_resize: 960
        local_feature_matcher:
          type: lightglue
          lightglue:
            weight_path: LIGHTGLUE_WITH_ALIKED_N16
            feature_name: aliked
            min_matches: 15
            width_confidence: -1.0
            depth_confidence: -1.0
            mp: true
      - type: local_feature
        local_feature:
          type: lightglue_sift
          lightglue_sift:
            max_num_keypoints: 4096
        local_feature_matcher:
          type: lightglue
          lightglue:
            weight_path: LIGHTGLUE_WITH_SIFT
            feature_name: sift
            min_matches: 15
            width_confidence: -1.0
            depth_confidence: -1.0
            mp: true
  
  overlap_region_estimation:
    method: lof
    bidirectional: true
    bidirectional_merging: intersection
    bbox_expansion: 16
    border_padding: 8
    lof_n_neighbors: 100
  
  masking:
    make_watermark_masks: true
    watermark_overlap_delta: 10
    watermark_border_delta: 30
    rerun_overlap_estimation: true
  
  shortlist_updater:
    type: pre_matching_topk
    pre_matching_topk:
      topk: 3
      #path_length_for_additional_pairs: 2
      #satisfied_edges_threshold: 6
      global_descriptors:
        - type: dinov2_salad
          similar_distance_threshold: 1.1
          batch_size: 1
          num_workers: 0
          dinov2_salad:
            weight_path: DINOV2_SALAD
            image_size: [322, 322]
        #- type: cvnet 
        #  similar_distance_threshold: 0.6
        #  batch_size: 1
        #  num_workers: 1
        #  cvnet:
        #    weight_path: CVNET_R101
        #    depth: 101
        #    reduction_dim: 2048
        #- type: dinov2
        #  similar_distance_threshold: 0.2
        #  batch_size: 1
        #  num_workers: 1
        #  dinov2:
        #    pretrained_model: DINOV2_BASE
  
  local_features:
    - type: lightglue_aliked
      lightglue_aliked:
        weight_path: ALIKED_LIGHTGLUE_N16
      resize:
        func: lightglue
        lg_resize: 1280
    - type: dedode
      dedode:
        detector_weight_path: DEDODE_DETECTOR_L
        descriptor_weight_path: DEDODE_DESCRIPTOR_G
        dinov2_weight_path: DINOV2_VIT_L14
        detector_model_name: L-upright
        descriptor_model_name: G-upright
        num_features: 10000
      resize:
        func: kornia
        size: [784, 784]
        antialias: true
    - type: hardnet
      ignore_cropper: true
      hardnet:
        orinet_weight_path: ORINET
        keynet_weight_path: KEYNET
        affnet_weight_path: AFFNET
        hardnet_weight_path: HARDNET_PP
        detector: sift
        num_features: 8000
      resize:
        func: kornia
        long_edge_length: 1024
    - type: mtldesc
      ignore_cropper: true
      mtldesc:
        model:
          weight_path: MTLDESC
          detection_threshold: 0.3
        topk: 4096
      resize:
        func: kornia
        long_edge_length: 960
        antialias: true
    - type: sfd2
      sfd2:
        weight_path: SFD2
        model_name: ressegnetv2
        use_stability: true
        max_keypoints: 4096
        conf_th: 0.001
        mulsitscale: False
        scales: [1.0]
      resize:
        func: opencv-divisible
        long_edge_length: 1280
        antialias: true

  local_feature_matchers:
    - type: lightglue
      lightglue:
        weight_path: LIGHTGLUE_WITH_ALIKED_N16
        feature_name: aliked
        min_matches: 15
        width_confidence: -1.0
        depth_confidence: -1.0
        mp: true
    - type: lightglue
      lightglue:
        weight_path: LIGHTGLUE_WITH_DEDODE_G
        feature_name: dedodeg
        min_matches: 15
        width_confidence: -1.0
        depth_confidence: -1.0
        mp: true
    - type: nn
      nn:
        match_mode: smnn
        th: 0.80
    - type: nn
      nn:
        match_mode: smnn
        th: 0.80
    - type: nn
      nn:
        match_mode: smnn
        th: 0.80

  detector_free_matchers: []

  reconstruction:
    use_localize_sfm: true
    mapper_min_model_size: 3
    mapper_max_num_models: 3