model:
  backbone: timm/seresnextaa101d_32x8d.sw_in12k_ft_in1k_288
  pretrained: true
  num_classes: 100
  drop_rate: 0.2
  checkpoint: "/home/longpm/works/selected-topics-nycu/hw1/checkpoints/seresnextaa101d_32x8d_sw_in12k_ft_in1k_288_imbalance/epoch_020_acc0.9567.pth"
  lora:
    enabled: false
    rank: 8
    alpha: 16.0
    dropout: 0.0
    target_modules:
      - Linear
    save_lora_only: false

data:
  train_dir: data/train_strong
  val_dir: data/val
  image_size: 320
  resize_size: 360
  crop_size: 320
  batch_size: 16
  num_workers: 4
  use_augmentation: true

training:
  epochs: 20
  lr: 1.0e-6              
  min_lr: 1.0e-7
  weight_decay: 5.0e-4     
  optimizer: adamw          
  scheduler: cosine        
  warmup_epochs: 0
  label_smoothing: 0.05
  gradient_clip: 1.0
  mixup_alpha: 0.1          
  accumulation_steps: 8
  freeze_batch_normalize: true

output:
  checkpoint_dir: checkpoints/seresnextaa101d_32x8d_sw_in12k_ft_in1k_288_imbalance
  log_dir: logs/seresnextaa101d_32x8d_sw_in12k_ft_in1k_288_imbalance
  save_top_k: 10
